name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  windows:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v7
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cmake --version
      - run: cmake --workflow --preset debug
